### ISSUE TITLE
Determine premine value

### ISSUE THREAD

**Issue by macterra** [cryptotechguru/Cryptonomicon#32]
In #14 we decided to decrease the premine value from the current 1.3 million tokens (133094593368744 sats to be exact)

What should the new value be and why?

Opened [multi-vote](https://github.com/cryptotechguru/Cryptonomicon/wiki/Vote-32)

**Comment by Snappaz** [comment]
1.3M-Chris-Marc-Nathan.

Or add up the ICO investors + Presale investors + amount for sale in Token sale (Up to team to decide) = Pre-mine.

I don't have the numbers for the ICO investors + presale investors

**Comment by macterra** [comment]
I propose 2 options: 500k or 1 million.

**Comment by Flaxscrip** [comment]
I liked the suggestions we saw here on the channel: Allocating a period of time when we would recognize owed EQBs from the ICO (using BTC transaction as evidence) and SAFT (using contract/picture evidence). 

Since we don't have a comprehensive list of EQB balances, people would need to come forward to claim their new TCT tokens.

Any unclaimed TCTs from the premine could be redistributed, funding pilot projects, etc.

**Comment by macterra** [comment]
Deadline was 2019.05.10. Should we extend or close the vote?

**Comment by macterra** [comment]
Current state 
![image](https://user-images.githubusercontent.com/434644/57797704-0697a500-7719-11e9-8af7-9529fe1bacd1.png)
